# Generated by Django 6.0.7 on 2026-08-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sskapp", "0004_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="location_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
