# Generated by Django 5.2.17 on 2026-09-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sskapp", "0005_post_latitude_post_location_name_post_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="location_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
